[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://neighbournet-42ys.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = ":host" }
[[redirects]]
  from = "/socket.io/*"
  to = "https://neighbournet-42ys.onrender.com/socket.io/:splat"
  status = 200
  force = true